const APP_ROOT = '/the-event-app';
export const LANDING = APP_ROOT + '/';
export const SIGN_UP = APP_ROOT + '/signup';
export const SIGN_IN = APP_ROOT + '/signin';
export const HOME = APP_ROOT + '/home';
export const ACCOUNT = APP_ROOT + '/account';
export const ADMIN = APP_ROOT + '/admin';
export const PASSWORD_FORGET = APP_ROOT + '/pw-forget';
export const CGU = APP_ROOT + '/cgu';
